#cloud-config
packages:
  - curl
users:
  - name: cluster
    ssh_authorized_keys: 
      - ${ssh_authorized_key}
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
write_files:
  - path: /etc/rancher/k3s/config.yaml
    content: |
      disable: traefik
      tls-san:
        - 10.0.1.1
      bind-address: 10.0.1.1
      write-kubeconfig-mode: "0644"
      advertise-address: 10.0.1.1
      node-ip: 10.0.1.1
      node-external-ip: 10.0.1.1
runcmd:
  - curl -sfL https://get.k3s.io | sh -s - --kubelet-arg=address=10.0.1.1 \
    --kube-scheduler-arg=address=10.0.1.1
