apiVersion: v1
data:
    token: ENC[AES256_GCM,data:2wrAoXwxp8GAmMJoA3mzZNm8QEAf+eD9BgCtcSA1wODLFchKCZjbZw78lTAPRmdRvYylueeG2KpxtuuDccSk6R8c8BAh+ziffNoA1uknqJXV4HKMdIrF9A==,iv:iimbxBXmaFzi68/nCVGy/NU1oPnwluM1RQLelWSVGew=,tag:N+ftqvjP4pq8wzg7GiDKSQ==,type:str]
    network: ENC[AES256_GCM,data:krP+8bkKfSJsBngo7DZ83A==,iv:uVhON3PL+nCKcMTBGEEl855jmHyzWgCaOLtUmZf7ecE=,tag:ak5krn6QLgRlZATos7Yp3Q==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: hcloud
    namespace: kube-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-10-16T18:50:29Z"
    mac: ENC[AES256_GCM,data:AepKK0NBkmEA9aFP/8a1I6RT6Q+4HR/vy/ellrCa7n5eFoYwG5bL+PwyuCraooXGDiSNqM0CLsX2RaG26uvyKNORACOPyT1CypjaGj/Y2U6pX7Bo9x1z/WvYNHUw1mWVS2iWaR1TIMzkUU0DaemOQGBkbRRjWfdPUmLHvmMOpkk=,iv:49VZ4XUXWjidNFtJewi+O3rgWoMs4LyGkQhzYYAXfhU=,tag:aPkla8pGIm92WM99SILVAQ==,type:str]
    pgp:
        - created_at: "2024-10-16T18:50:29Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAysLiv07AHPqARAAleAyP6PmAP6oxfoTw04g7/M2MKZFaNgSZzwFobAo5LO0
            T6g8wUjApZK76ViLQ/Q1x/Hu5aAV8bsA2Jkwy25mPMa38YlmgJ2LsXkMVQY3jkoU
            MUmMu71kp4wa3Yct8q7AYVnMLlShibVqd6iJnbpl6WghNiPnXMrf3Sl3JU+jKXBJ
            6DCFuL3TqyNhFPiT1BPCWzHSnxnjZdUSSkC14jqLG0vP3Ps/FIQgeSmSQUtWIbFS
            /4/iQqMDSu8RkVwMxsD0XbXh5iAhhNPUu1ujHoJDv2mdhglSmBL+Job4CGnhdgn7
            hUocrzrpxuHCBIB0R2dqcHGVN4EzGW8y8Wf4s3oW1gIpSZG8aUNtuARBljavSMBk
            OIF2a4EbgAJCKrAEuxSr5VgLFGMsx+SxNfbIP1frfLIWcm9HKeiAHpbNHubNjkdU
            YgOJTRxccVN3ulDEvlpDOrJA4NmnnPuUv3Anj/7QYIxroF/GT4K/WMlOZKazo5W6
            sz2kGF1ima+ncUHoemtmdcG3PyO3FSkrCEqtDZSHzm4UsAzUHyqZGrzzeykjYThD
            fdaAp4J0eUfUNmgQZPCE8s1ak1ZlIl+23gxAsnrZtgPo3WP1Cfal98cxY1Q+X/kf
            gdSv1yLCPSyPb1xo15G//HXPYzMedS+J8LhDNypCzutd9kcB20kbYv8amoz0iz3U
            aAEJAhDibYwKAcllht71ZqRpl/8AR5TSdFrEOdNXKFRxEo7zhyi4FtuUVsf97RuQ
            RBy85OP4YESL+v6a7i++uSNAsZTuaz98mW2y6fsollewuF50YIPDf/G9mTCWJcoO
            lYp+NNoGLlnh
            =XszB
            -----END PGP MESSAGE-----
          fp: 427B2D23D5B5520342F0FE825DDB497AADABDF0E
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
