apiVersion: v1
data:
    token: ENC[AES256_GCM,data:Rw4P56smjsi2je0Mg6Lw6BYr6/eQEqT0JlD/km1v4mKt+TtoY9Ims2bfirKtdINzFtAEnmHHTKvpa6yL44S70ekPIMZ3pl1g1UNPsUz6O0b/lEW3cRjmxw==,iv:ZndipWc3DRyfBCTuG/uQUEKPRFq/RWozaAFMLFkNU4Q=,tag:6GfGBD02wEPVbjJBeUsGUw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: hcloud
    namespace: kube-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-10-16T17:25:49Z"
    mac: ENC[AES256_GCM,data:ypMgNa8DzyQUSzjApE5Qw2Q69xRwT83UhvnzjFr/rPas3vmH3MjY4YV2eGzJ1V5V+2UYfQbLOfBBVH4uAdPKqYBg8lZ3bJCgmjWeXxdAZL3mlr++BpbRd2EeQWgiU0Mt8CRIaftNOjR5KV9mX8O7oTr/WSAg6hD5Wk6ZF8prKJw=,iv:FpgI63IqDbSTrqkttGse6J1BOnOiM7MfVkzO6Pt2u4Y=,tag:ulL3kwDqzr4CFLrO8+xT+Q==,type:str]
    pgp:
        - created_at: "2024-10-16T17:25:49Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAysLiv07AHPqAQ/+L2eJa+8tIfjtb8p+jsuKx+uGc4a8r3yO41TD0+iUPf3c
            abBRuHDNGtl7sv0rKq1h9F14Kx7DwbuxUf/BF1nhSrPsbayOLGVUBmYSpEwK8ySE
            Gv5Y4ZfRLD+n/x8OuBImSU7J1FkQmZRvirOoilNt96gansokymx2pDTA0MGOHFjF
            FNAQ14xWlstjMlcuzYMEAf2YZaGkB0rTPEcBIk5cC6+7XF/Pl1zutWOuQ55x9Jz/
            xJWptVhYZvTT1ftw46yKs1EDoMSxHpmk9N/JYM6ReyuvrAuSzPYwx0iMWIjf5ErN
            CXt6zzt+fURpgvLHuvmLgezuzgzWC3cMHW/qqzSl89oYIRJwssF7iLTaEY3b3l4b
            UKz/UGX0QLYDgwnp2WAZAbTagJIqWiElTFQulmdkVV2m5hXM7oow5dBXjeBjazHi
            Rh4B/tKJhsvgQm6bQ829XyqQYqpmeiPHh25isyXNTq1cTXBS2qeuPEskNFCQ5Ugk
            xwTcBBuqX9bg/yExYgqvS+hmFX9FVr3ONWzEKDW3DSoAz3XK6RuQC9vrp18Co4dH
            eBSNEKgveeTrebtrUvTQA6zOpSknKlQBXWdOmPt7HUjasI15QPQA96Ardvg23r42
            FdQCEn6iW57pgY+14XNla0WP802w979THeqfX+m/qpMzpX4P6fgCLRXgEZCJ3UPU
            ZgEJAhDt+DfTsT8wqlxa6IxZouIrTIDOR5LG+t4Hwfej+HtOF4kB+8CHIeq2dX7I
            2giB+jRyPSpLUekwT6l9jIykRIXtt815fSM+Z6wt8fKsIWzhx3+3cJrM9dMvWfQB
            GendWjp1IQ==
            =Us4d
            -----END PGP MESSAGE-----
          fp: 427B2D23D5B5520342F0FE825DDB497AADABDF0E
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
