apiVersion: v1
kind: Secret
metadata:
    name: netbird
    namespace: netbird
type: Opaque
stringData:
    relayPassword: ENC[AES256_GCM,data:BTGn5nCYSf879irWYihI0YBCNIAmwJRycZWy8YyY7v+fEv+iCI+1E7UhyuE=,iv:gtR3XyqtsABpI48zz3U3OV7Bm8lm4CRyKhDFj7Vu6OA=,tag:nAqkQK5KWicI6q/fRTqBoA==,type:str]
    datastoreEncryptionKey: ENC[AES256_GCM,data:VbTT3XqYLTO4BRjvnKXiU8AMtpCzopyeaBlNsqRMHqJxG3u5DcKbnvpNHWk=,iv:C1Yad6Im5CMkCZTI70JQLJ6VeGCCMlFvfVgcD/hlR1c=,tag:WlHJ8V6igtvCglIETVuZtQ==,type:str]
    encryptionKey: ENC[AES256_GCM,data:vWLVL5TWa/vV20uRp/YFYBrwAuESr5Ob4RVfBh+iDGDVgeEL31QBbOQY/r0=,iv:QMVUe9/tWYdTobkKfC4BBvOG/9kSqPhT9jNMOX/T8cg=,tag:NAUF/3ezFGSdIridVWtPqw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-04-20T22:11:44Z"
    mac: ENC[AES256_GCM,data:jUxmYAGAyuNNMKrsZti+HGh08TKzbdXR09ieQKAi45xvwmoGIRn/eqZVQgLS52ffXzYPapqc0PMKaF4mCzEv4HhQWz27eVMXGP8wCUfF0HE+o9RKOaz4Lmh+sbcVcFo19UbXEfD2wCWWZabaCnVJos9XOhIPyGFtxsZBZYRH8zE=,iv:/75/Z5PngeAuNrVsGcKBMlagRIuHdg7Iwy53VfbR/KU=,tag:YENUOLlwph7y1DV0zhtr8w==,type:str]
    pgp:
        - created_at: "2026-04-20T22:11:44Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAysLiv07AHPqAQ//QBUCJfwHqcA1TAvigBKEX8FlNitYEYqvoRdE8kI+7oFf
            40GZ0mwy6ILJQGol+H2t62EGtbuJPDFcQPJdJbedItAbHq2lZ8HwgQSub/Dan74j
            Zr/6ad+gOLK8uIXsxnAo1w7YBfJl0fLVfPE8Jg5E5b2Hk385eELqOEKMcrAbw095
            cEwTM2VPHvzLDg8hhxlsX7ASOLaeO0iEEDO0lbBY51vTV5SootcFACpOrXmI1V33
            ectH7+XeSxSPm4OMI56Vbd6mgxHQvHQaTKdQj4EADX/44gmabZGuk1KbaOi/K76S
            CYk7xo/DBi6K98vG+aBuJjcOe0OxTltds3VLp1E9OwW36Vo8x4gWSIQEOUieS+Qr
            jFn9RK0fDofKLIRuTAv+jdMpPOboV8575xR6QhnXHPpfiudNbS0mc+RD7Bcliqff
            vkzdGwV0NZyPMSCloRU8OuPiddysYUqmDcsZ9PW28z5CqKFElI7DDGWCH/8zZfTa
            8zW5zv9Uk7I6Oie9OIM6VVqbyVui2rRoDyTk7bvM+2q/O3KYz0BGQbmAmX3Kh7/e
            iCggq+vdO6cpnYiaFw8sO6LXG4geZZbTCQO6zqvkrCuobNpy5Vwean0LyifNIv3W
            U5dOS/79Dj5mj65pnrCiMkaVg6OQE73jekisurxFX97OEfOyLHDH8D0/s5AXyjfU
            aAEJAhCBUQ92cWJm9l9Xh6bczxx4GTmNJJk5AbqJWIaG2OYPKNCI4LAOBFpVkLZP
            gGhsQF+HtnPr7pp2h0aOWbAG2OEI4mNjpQvAZQcOPF2YxrTGDHW5bSCbu/SNba5M
            X+b074FQ0Kv4
            =0wVC
            -----END PGP MESSAGE-----
          fp: 427B2D23D5B5520342F0FE825DDB497AADABDF0E
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
