apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  test:
    enable: false
  values:
    ingress:
      hosts:
        - host: podinfo.local
          paths:
            - path: /podinfo
              pathType: ImplementationSpecific