apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: podinfo
  namespace: podinfo
spec:
  gateways:
  - istio-ingress/istio-gw
  hosts:
  - k3s-0.marianobe.cc
  http:
  - match:
    - uri:
        prefix: /podinfo/
    route:
    - destination:
        host: podinfo.podinfo.svc.cluster.local
        port:
          number: 9898
    rewrite:
      uri: /