---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    # Email and server are set on a per-cluster basis
    privateKeySecretRef:
      name: letsencrypt-istio
    solvers:
      - http01:
          ingress:
            class: istio
