apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: istio
  namespace: istio-ingress
spec:
  controller: istio.io/ingress-controller
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: istio-ingress
spec:
  acme:
    # Email and server are set on a per-cluster basis
    privateKeySecretRef:
      name: letsencrypt-istio
    solvers:
      - http01:
          ingress:
            class: istio
