apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: istio
  namespace: istio-ingress
spec:
  controller: istio.io/ingress-controller
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: istio-ingress
spec:
  acme:
    # Email and server are set on a per-cluster basis
    privateKeySecretRef:
      name: letsencrypt-istio
    solvers:
      - http01:
          ingress:
            ingressClassName: istio
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-cert
  namespace: istio-ingress
spec:
  secretName: k3s-ingress-cert
  commonName: k3s.marianobe.cc
  dnsNames:
  - k3s.marianobe.cc
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer