apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:XpICsfAaoAFAhE3EYXvR11aOkmrGUw9hah3ZJz/VXoVPjL6y0EvOHBCyzyzRVMErh8vUTVdAGxigiAbNGVN2bH8MtUMkRQ6QOVfpz/Lod9qMX2ORtiLExlIhHjP+sYXH/z/Y1yQtC6Blhw7zoDwGOBxeY+XI56dY1c+JaRpH+jfNjJW903ySFTEnO9Zf6BOijKZfLl+LSAtqSbTJNCAnnIPq6uI/vN/Fa6EZEpNPkNydpr5aOctvWcC3R2SYk9wQ8RfdMq0ioWzcukgz6DKz0E3LzTnW/BL1fUXK5tqS/x7w1wrZy+wt7loxztt2k83Pyu44aiiltBDrdHT5A2hY1GRpk1krNqCK+Rn+HOy2BWJ7frlzVydYWSM/5RT+tiuJIFTsXoYtSIqpw/FoKCbINuwvEwisNHsoACKBYhm1tNrYbYpg4OyH42/oq0fV7puPuRVnls8dmMXuYgd+ACdiSibE0JlPzo6dyuDDAdBhANIEey6LR7cVmZLuSNhP90g758W42RPMUk9MXatn5xvh7H09Mq6RLq4nXzsyK+Apk9aVD94b,iv:AyhN/XpFLNdRBTspCYpoSS7V4LIJ3NPgAaTDoXH25Ds=,tag:j8/2dMfuGGWm8TmZkhfKgw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: cloudflare-private-registry
    namespace: restic-backup-checker
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-04-22T01:07:54Z"
    mac: ENC[AES256_GCM,data:Dl+ETJuJHdx2GInNVRGKt2PwrTj6pOm2CQDDqh1LwUYv2FOgoWLEzRS/D810vU2kIUegXYl0VKBDewmXSGRKSHq4BTWJB/5lIGmHnMrwMDUlJmoybrzMZiKE/b9UV+IYuNT5Cp3xEOxOorNnsDHsJBtWSZ0OQmGx9pJzPKYmZiM=,iv:dM1s7Oq6KStxiYAZL8hf+SEmy3P9zDMjeFhP4FodWuM=,tag:CQ/nG2gWOi+Lm8fKFU8BLw==,type:str]
    pgp:
        - created_at: "2026-04-22T01:07:54Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAysLiv07AHPqAQ//SWJwY/ISQC1AaQHwYx6FHoFsonbvxeuM4XSjDNjqdLMR
            n2sYvYyWKmVAaIe47Atdw6+05elKtU5ozo2Mnsni8BnyJzj2/d0SHdjOS4P2SfpX
            NrnCcCA2e+jZpMMw2FoNvuetfZOwrXcSdlfy0m17i+OKtuk0j3KP53aSkvhnrDZc
            FUTCHt1jiAeE/ukbdkvF0xZC32T7kncDzHSIWEcRXHWFS+q7oYcXmZ3/xQuQ9gZj
            dBwnq8kwy7t9KunKfSgo2YNLxCF0md/aN4Ux23Wulq/MEblYclCI5J7JE6oHRQdY
            rmLFdJAhujX+hzN/pJ9G0NujcjWEjfS47pWENrmXY1LgrsGSYxGWGPS34MSEu3KI
            A/zJAdNaSuKiKlby6ZuQwJfQ+wtY6uomAJ99t61gTU4LbrZ83dizR2+z8l6grkiO
            /iiwawrqdc++knBy39SjhJCbe3oo41Ajn+IAXMlC6yZKSR7ZJkPzjTevxbb7P59x
            nMOY8YsZ7Ihh1Wu+uG45fXWVkIg/O2peGiV220I5B0jomnSwksplx9+MtEBgtaUa
            nLEKUx5xxHcuJ9Yd+1yhCTcLbetSIEv5RmeZGw/PB95byoaJF1n2KzUgGhaOEHg6
            7JrQo2o1dpQnBEYmPxIBFK6WziqidgvsIUMT8gP552M5W/LnMeUGUdmarjqhkCvU
            aAEJAhC5yFcKwB8gcqTYGWEhH89jCEA5GoUoyPNAiw2LhvuJZ3tmbLoichpv8gk8
            G9bikkz75HHw0VK+tI2rwHmVwXI1OadiUFL/MJzJH2IPmfih+zYq5IiZa8dgyMTW
            f2qEjTUjsiFS
            =aE8q
            -----END PGP MESSAGE-----
          fp: 427B2D23D5B5520342F0FE825DDB497AADABDF0E
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
