apiVersion: v1
kind: Secret
metadata:
    name: restic-backup-checker-secrets
    namespace: restic-backup-checker
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:m3eptpB0y6e3bI61vo0cD1cxBI7nGjtKR3H4ZT/uu1Q=,iv:MREaywm7zHCgdoIt+VpE/uywKa6xT+J7/w/z59uuCdU=,tag:ZfTbjSzhosCv/BI+KSYfnQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:m1QZrvjCOCXODek+WPgx4C3+gCZABFUj5EGgPq7Mv7eBFlfMNmdSuksXiSmjZSKfoFGuF+YPBVT2kljipjlZrw==,iv:Hi2+FqzaHaJc0Kub5U1qPZLdkKApWsZfAtwETx0q9fU=,tag:WXzOxebYqAB1qeb7AGfLIw==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:0hcDGUQ0Iuq6rzEa6E6GClIL0YMnS4ArnBw6E9uzOM7PrOgQp6ABvqASW+NJ2i7n7EZlF9oc1fqT5Iv/hbm9AHSwn7Tj0uJ1n156Rw==,iv:FU/OTSqy2kVBzWgiDieukUgDo+p2tQKC+6+kpOUOujY=,tag:i93RyLuoUqOt0NhS+eehGA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:Cg+JXcAteebDwFBTujY=,iv:HV7r3U3QKh04KOJJbT378ogsk2X9FqoySnVFpPPsa+A=,tag:QtsiHYq9tj1pabqrxTqV6w==,type:str]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:lLBPwP14DU8MM2f2UfO5iYfcjoALeGmHgColKVaQGM1tpyPlG5AWE+WAA1Azqg==,iv:pjeJcLDBrUskvCtI0sllaBuBbcTx3o3fnApyp+7k6eg=,tag:LVONw+vYqM5rLkoAzBBb1g==,type:str]
    TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:wG7KZhgd4mR6,iv:xMmRN/6IoE2DNZQrZt5AmhBcT6zPNNyHPto+BhgLpzQ=,tag:x0yOh/lG32I/jtpWKgtwVg==,type:int]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-04-22T00:54:00Z"
    mac: ENC[AES256_GCM,data:LzCA00FpcVoLh6n5n7gUGMTHq1r2P8oRj6XqiT+kIHUkKin+COXHuGVtR5vzubIzj96/CNKLzr1gjMixU6Lk/2DZJbEfgTPJxqnv/AgZZ7VU7EcKcOq8cgroYjYAG25djapcWu6JaMx3zWn198zzPMjo/xUw6rdEe68KQRLTYBk=,iv:IqEkOYeba57gZ5xNIgydg09HFizkasx9CRaMVt7ekwA=,tag:O5L2G1m+CZCeylbMtpAK6g==,type:str]
    pgp:
        - created_at: "2026-04-22T00:54:00Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAysLiv07AHPqARAAmkLS5VAWiH6QWmbveaaV82Bd5Q4OTuKgCyaO3e0ehwac
            AQFtHQ/05dH5otXZ1jkRtuE5/NWXeGn8zzLm70WgSD1aRpE6xvZ1jDb417aAyWez
            JdbXEBH+gunIgzhrYMVe/U/lqQIhNZf8Q7tdYuoIkAygejpYAPS7QMrOsyRIMdws
            XIjmW8EG5shCJAbcIrGxWFavnczrnAD2Er0MBkxnRcCnSSYxhMPI8JEmxuc3jVAw
            piWvWthOcznIbKPM8t5kINqCXW+M2NEdlBOobFf2ce7b6bzesWcZ4z55KivioQzk
            zUg9aNBQK45KsUKY4pCeOeayswn62czWSe/7p/qcFwbIyznOpkaECq3SdXvWQS0b
            2D5GV8ApA++bYB5E//LjQk1L3chMDT75iuQEJCKtw8yc7eDUmkEr9yIv1345v8lw
            PRgsaJANncfGMXn5RUur4W9YBURXqDYCQgWPrXmCI1u04FlNkwPq8LJdZATMAJjb
            O9huueNmWETuYD1qyVsiMnZIHWTLf97xBIkxEGZpIE1Xvam2noGeUIOsq0Qz3ewF
            61ua4SO5f/Bk2ClH72MwgzhgdhnRFNhtUFC86HV7F8do+6gMQ8zpSWl++z6K6qQm
            9cTzAzq38jYXWPT7qx+xOwT0pEhxXHPxoYIcR3s40R0ZeqUs4qHtepplorgXzwjU
            aAEJAhAd0+dxA+iR+9TH0XEbLS/YR0ma4NpxF7iDjTli7cFI83b6tjLHQMdmH4zh
            +b3QdPviy6cmaPrR9Db8OYxWJgJTn4issRXuOZs0fvS2+8BPzW1T9F8Dx9qsq0gp
            8SRz0AQBgym2
            =A5a6
            -----END PGP MESSAGE-----
          fp: 427B2D23D5B5520342F0FE825DDB497AADABDF0E
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
