apiVersion: v1
kind: Secret
metadata:
    name: restic-backup-checker-secrets
    namespace: restic-backup-checker
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Q5qWv1NJIh8fc+byWM7IOqh9Z5dWohyAUBfbOHFykwo=,iv:5WJbCq4QF+I90UuZcko4r5+sUQBfwBzjQzJ3FjxqjaE=,tag:+etmWkUC6i2EIwDW3wPJqQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:1wjMdgFYmcNlXa6tK9+dFCV1+ZSAtOxPux8SH+lVdpDKU87Q+syIF8jb2Jv7mwq5nerNpgcD6pAQNsLjyviSKw==,iv:PJRBsWva384aOw9VTwVVPF//wlz7Hj+ulT1V/k0Fo1Q=,tag:wuJ9eaz59/uk7/0HwUmPFA==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:yfWgy/Ln/vHmgb1tnjxAdn9duk1ZlreyUPlb3Cc/EZgWA1gi2mIJbVqx9czD64PoZmYqn5pXOIPy+ZyPVzAOs7z5ZeQt6QH1XdCCwA==,iv:4PNCoZq8Kvs5BeIQMzv0TCxnd/SQgVcaq+RPw5z155k=,tag:XGoYH+e56qIgT17H5DvhGQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:g31EA2BJDQixUZIAln4=,iv:YuejPlyYxsd76+mwetjH/KM1FfxzRcQCuR0C14upVAU=,tag:nCsC7C1a/7CibYiieehMkQ==,type:str]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:QhB8zkG9HcEKLKy8trenyjJTHlWcbFbq6YAg8lsEWCVvUBQfRqOTJ+zLBvK+WQ==,iv:wVd6sUUD+xMb7R2nyiCWxoGqRR81aXXGRK9IQNOsQgk=,tag:xYkIdGG7d8l9VRzwz+kFog==,type:str]
    TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:gxFa+3rp6Ke/,iv:BcrITAI3wDmOWFN6T2ePXHoiQF6XAuFiw1Eg9Jt7kbs=,tag:bcSj0qP+CABgjhYtOABdiQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-04-22T01:37:42Z"
    mac: ENC[AES256_GCM,data:gQgJ2SM2x+cNvEAm8PFdp1DQke2d43lFoBtlbumxdo5PT1+5JSsPlYfhoi1fmuWgMfvKMlBx4rGZYjDIpGiC2UOwlSxdGv7i1r5aotH+tGAoboGBE1N5jieQ9zbczQDgHezx0ek9A3q747TCSta154deg5kPbLp5seuvleH+BbQ=,iv:Eo+4i2Jtog+oY4QJqOGNEM8C6AYk/0L/L22qY8xlMeE=,tag:kd1NFeRwxdtteWw2CjJhlA==,type:str]
    pgp:
        - created_at: "2026-04-22T01:37:42Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAysLiv07AHPqAQ//dQtppRFRRIAKUp9YQhGm9ZhmZeLOAWn79tfkZs7dsbiD
            CcbtTAJcNIjHfBHYJZssZnN6NQV6u13XTkCQispWlSQo/iG2SixDa6HEFL00S9Pv
            sU2jPcltgLZr30ymHjTlKM+nV9FGRuX0KEF9gjn7eseJzHn7V/fE1c4UU8xwMX2C
            tqGtlR7ms5S9PiZPHmayX2XsfpcRnUi2pKp1Rd3sIdFYafP3W5onN3q7YgVn/oyL
            QPH2ALsIQGALQXbeJ9oUkHdoUcvUhRFRI0P6VtOWxdn7jLyPedQLwGkTe02l0dxY
            +y3o72XocfE2yrI+20OjSuCnigx3r90oG7ifP/742xBp3RKLQfa9q1mpPhh5CAiG
            e+iTVLxcwJ/rrHcZGptkc45+d9U4/hZJqV6J0R+UE3RLAs9x8iDgkooTr7WDgXpX
            mCgpp5eOcmfPWIuEDYCXjHf5lWLaoOR7D3Z83gwH6C/u3hDTwQZORhDYi+zucHml
            gIThVY1XoIFCccXwolqH0mMTmeCGRkRCeVubd3MS9t7BKmnozTcuxpFbRjNerIau
            cDxKC+QWDkJULWsHirzdWcRJu1v6TJmxY+rQx/RLa4+ZcwjWDt2kEaNmTeV9qBOy
            2VUOHj3Km4Ink4n7LK3dA+QMC+RDVaWf4Fdt+sXKCe1vEsyuEmtPGqV9oZZOEuHU
            ZgEJAhB8a4ErIzaquAjrsd9uA4nnsYifPSHsjM+UP/t9fSLThYeb1uKZ2Sq8kVAd
            QJKPcHXkjgug58SZbbuRmj2Wt+RXXp+yIZl6FnymZ6TjGFsO6cbmJYDM8Wzd0o3x
            RnDXq1as/g==
            =iQh/
            -----END PGP MESSAGE-----
          fp: 427B2D23D5B5520342F0FE825DDB497AADABDF0E
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
