apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: istio-gw
  namespace: istio-ingress
spec:
  selector:
    istio: ingress
  spec:
    servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - k3s.marianobe.cc
