apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: istio-gw
  namespace: istio-ingress
spec:
  selector:
    istio: ingress
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
      - k3s.marianobe.cc
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
      - k3s.marianobe.cc
    tls:
      mode: SIMPLE
      credentialName: k3s-marianobe-cc-tls
  - port:
      number: 80
      name: http-acme-challenge
      protocol: HTTP
    hosts:
      - k3s.marianobe.cc
    tls:
      httpsRedirect: false
