apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: istio-gw
  namespace: istio-ingress
spec:
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
      - k3s.marianobe.cc
      - marianobe.cc
      - www.marianobe.cc
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
      - k3s.marianobe.cc
      - marianobe.cc
      - www.marianobe.cc
    tls:
      mode: SIMPLE
      credentialName: k3s-ingress-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: marianobe-site-cert
  namespace: istio-ingress
spec:
  secretName: k3s-ingress-cert
  commonName: marianobe.cc
  dnsNames:
  - k3s.marianobe.cc
  - marianobe.cc
  - www.marianobe.cc
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer