apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: istio-gw
  namespace: istio-ingress
spec:
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
      - k3s-0.marianobe.cc
    tls:
      httpsRedirect: false
  # - port:
  #     number: 443
  #     name: https
  #     protocol: HTTPS
  #   hosts:
  #     - k3s.marianobe.cc
  #   tls:
  #     mode: SIMPLE
  #     credentialName: k3s-ingress-cert
