apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: istio-gw
  namespace: istio-ingress
spec:
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
      - k3s.marianobe.cc
      - marianobe.cc
      - www.marianobe.cc
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
      - k3s.marianobe.cc
      - marianobe.cc
      - www.marianobe.cc
    tls:
      mode: SIMPLE
      credentialName: k3s-ingress-cert
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: redirect-https-except-http01
  namespace: istio-ingress
spec:
  gateways:
  - istio-ingress/istio-gw
  hosts:
  - "*"
  http:
    - match:
      - uri:
          regex: "^(?!/\.well-known/acme-challenge/).*$"
      redirect:
        scheme: https
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: marianobe-site-cert
  namespace: istio-ingress
spec:
  secretName: k3s-ingress-cert
  commonName: marianobe.cc
  dnsNames:
  - k3s.marianobe.cc
  - marianobe.cc
  - www.marianobe.cc
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
