apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-ingress
  namespace: istio-ingress
spec:
  interval: 1h
  dependsOn:
    - name: istiod
      namespace: istio-system
  chart:
    spec:
      chart: gateway
      version: 1.23.2
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  values:
    service:
      type: LoadBalancer
      ports:
        - name: http2
          port: 80
          protocol: TCP
        - name: https
          port: 443
          protocol: TCP
    annotations:
      load-balancer.hetzner.cloud/location: ash
      load-balancer.hetzner.cloud/name: main-load-balancer
      load-balancer.hetzner.cloud/use-private-ip: "true"
