apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  interval: 1h
  dependsOn:
    - name: istio-base
  chart:
    spec:
      chart: istiod
      version: 1.23.2
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  values:
    meshConfig:
      ingressClass: istio
      ingressSelector: ingress
    pilot:
      autoscaleEnabled: false
      replicaCount: 1
      resources:
        requests:
          # TODO: patch these values in cluster kustomization
          cpu: 100m
          memory: 128Mi

  upgrade:
    remediation:
      retries: 3
